obstracle_waypoint_goals:
  obstracle_distance: {
    type: double,
    default_value: 1.0,
    description: "WayPoint and obstacle distance to reject goal_pose and stop in place",
    validation: {
      bounds<>: [ 0.0, 10.0 ]
    }
  }
